baseURL = 'https://aranjuezy.github.io/hugo-strapi-snipcart.github.io'
languageCode = 'en-us'
title = 'Hugo Commercial'

[params]
  author = 'Aranjuez'

[security]
  [security.funcs]
    getenv = ['^HOME$', '^API_', '^BASE_']
